#!/usr/bin/env bash

usage() {
    echo "Usage: $0" \
         "output-1.txt output-2.txt ..." 1>&2
}

if [ -z "$1" ]; then
    usage
    exit 1;
fi

for file in $@
do
    if [ ! -f "$file" ]; then
        usage
        exit 2;
    fi
done

tail -n +2 "$file" | tr -s ' ' | cut -d ' ' -f5
